export function createBaseColumnsCandidates () {
    return [
        {
            label: 'id',
            documentation: '常用表字段',
            insertText: 'id',
            detail: '常用表字段',
          },
          {
            label: 'id_id',
            documentation: '常用表字段',
            insertText: 'id_id',
            detail: '常用表字段',
          },
          {
            label: 'org',
            documentation: '常用表字段',
            insertText: 'org',
            detail: '常用表字段',
          },
          {
            label: 'product_cd',
            documentation: '常用表字段',
            insertText: 'product_cd',
            detail: '常用表字段',
          },
          {
            label: 'id_no_hash',
            documentation: '常用表字段',
            insertText: 'id_no_hash',
            detail: '常用表字段',
          },
          {
            label: 'id_no_mask',
            documentation: '常用表字段',
            insertText: 'id_no_mask',
            detail: '常用表字段',
          },
          {
            label: 'app_no',
            documentation: '常用表字段',
            insertText: 'app_no',
            detail: '常用表字段',
          },
          {
            label: 'ecif_no',
            documentation: '常用表字段',
            insertText: 'ecif_no',
            detail: '常用表字段',
          },
          {
            label: 'name_hash',
            documentation: '常用表字段',
            insertText: 'name_hash',
            detail: '常用表字段',
          },
          {
            label: 'acct_no',
            documentation: '常用表字段',
            insertText: 'acct_no',
            detail: '常用表字段',
          },
          {
            label: 'card_no',
            documentation: '常用表字段',
            insertText: 'card_no',
            detail: '常用表字段',
          },
          {
            label: 'cust_id',
            documentation: '常用表字段',
            insertText: 'cust_id',
            detail: '常用表字段',
          },
          {
            label: 'case_no',
            documentation: '常用表字段',
            insertText: 'case_no',
            detail: '常用表字段',
          },
          {
            label: 'id_type',
            documentation: '常用表字段',
            insertText: 'id_type',
            detail: '常用表字段',
          },
          {
            label: 'id_no',
            documentation: '常用表字段',
            insertText: 'id_no',
            detail: '常用表字段',
          },
          {
            label: 'cust_type',
            documentation: '常用表字段',
            insertText: 'cust_type',
            detail: '常用表字段',
          },
          {
            label: 'cust_no',
            documentation: '常用表字段',
            insertText: 'cust_no',
            detail: '常用表字段',
          },
          {
            label: 'app_type',
            documentation: '常用表字段',
            insertText: 'app_type',
            detail: '常用表字段',
          },
          {
            label: 'openid',
            documentation: '常用表字段',
            insertText: 'openid',
            detail: '常用表字段',
          },
          {
            label: 'acct_type',
            documentation: '常用表字段',
            insertText: 'acct_type',
            detail: '常用表字段',
          },
          {
            label: 'prod_code',
            documentation: '常用表字段',
            insertText: 'prod_code',
            detail: '常用表字段',
          },
          {
            label: 'prod_id',
            documentation: '常用表字段',
            insertText: 'prod_id',
            detail: '常用表字段',
          },
          {
            label: 'partner_id',
            documentation: '常用表字段',
            insertText: 'partner_id',
            detail: '常用表字段',
          },
          {
            label: 'product_id',
            documentation: '常用表字段',
            insertText: 'product_id',
            detail: '常用表字段',
          },
          {
            label: 'id_acct',
            documentation: '常用表字段',
            insertText: 'id_acct',
            detail: '常用表字段',
          },
          {
            label: 'id_app',
            documentation: '常用表字段',
            insertText: 'id_app',
            detail: '常用表字段',
          },
          {
            label: 'c_prod_cd',
            documentation: '常用表字段',
            insertText: 'c_prod_cd',
            detail: '常用表字段',
          },
          {
            label: 'id_cust',
            documentation: '常用表字段',
            insertText: 'id_cust',
            detail: '常用表字段',
          },
          {
            label: 'id_openid',
            documentation: '常用表字段',
            insertText: 'id_openid',
            detail: '常用表字段',
          },
          {
            label: 'id_wx_openid',
            documentation: '常用表字段',
            insertText: 'id_wx_openid',
            detail: '常用表字段',
          },
          {
            label: 'id_qq_openid',
            documentation: '常用表字段',
            insertText: 'id_qq_openid',
            detail: '常用表字段',
          },
          {
            label: 'id_sg_openid',
            documentation: '常用表字段',
            insertText: 'id_sg_openid',
            detail: '常用表字段',
          },
          {
            label: 'id_loan',
            documentation: '常用表字段',
            insertText: 'id_loan',
            detail: '常用表字段',
          },
          {
            label: 'id_org',
            documentation: '常用表字段',
            insertText: 'id_org',
            detail: '常用表字段',
          },
          {
            label: 'reportsn',
            documentation: '常用表字段',
            insertText: 'reportsn',
            detail: '常用表字段',
          },
          {
            label: 'id_batch',
            documentation: '常用表字段',
            insertText: 'id_batch',
            detail: '常用表字段',
          },
          {
            label: 'id_case',
            documentation: '常用表字段',
            insertText: 'id_case',
            detail: '常用表字段',
          },
          {
            label: 'ds',
            documentation: '常用表字段',
            insertText: 'ds',
            detail: '常用表字段',
          }
    ]
}