name: build-and-test
on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
        env:
          PYTHON_VERSION: 3.8.12
      - run: wnpm install
      - run: wnpm npm:prepublish
      - run: wnpm lint
      - run: wnpm vsc-compile:client
      - run: wnpm vsc-compile:server
      - run: wnpm test:server
      - run: wnpm test:parser
      - run: wnpm test:sqlint
