name: build-and-test
on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
        env:
          PYTHON_VERSION: 3.8.12
      - run: npm install
      - run: npm npm:prepublish
      - run: npm lint
      - run: npm vsc-compile:client
      - run: npm vsc-compile:server
      - run: npm test:server
      - run: npm test:parser
      - run: npm test:sqlint
